### ISSUE TITLE
How to run in GPU?

### ISSUE THREAD

**Issue by lakpa-tamang9** [mkocabas/VIBE#236]
Running demo.py automatically runs on CPU and takes huge amount of time. At the end, it throws cuda runtime error.
`RuntimeError: cuda runtime error (209) : no kernel image is available for execution on the device at /pytorch/aten/src/THCUNN/generic/LeakyReLU.cu:29`
In the readme, there in no any instruction provided about usage of CPU for inference.

**Comment by mrpositron** [comment]
Hey! 
How did you solved it?

**Comment by liubl90** [comment]
update pytorch and cudatoolkit works for me.
conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch -c conda-forge
