### ISSUE TITLE
256 x 144: CUDA out of memory. Switch to CPU?

### ISSUE THREAD

**Issue by caseybasichis** [mkocabas/VIBE#62]
Running the demo with a 256 x 144 video, I'm getting an out of memory error:

`RuntimeError: CUDA out of memory. Tried to allocate 16.00 MiB (GPU 0; 3.95 GiB total capacity; 2.49 GiB already allocated; 18.88 MiB free; 2.51 GiB reserved in total by PyTorch)`

This is running on a 4gb 1050.  
I can setup a 6gb 1060.
If need be, I can get things going on a 13gb 1080.  
Are any of these large enough to run VIBE?

If not, how can I run it on the CPU?  Is 32gb enough?

**Comment by ikvision** [comment]
What is the batch size you use? Reducing it will linearly reduce the GPU memory usage (args
vibe_batch_size)

**Comment by caseybasichis** [comment]
That fixed it. Thank you!

**Comment by Rakesh-Paul01** [comment]
@caseybasichis @ikvision how can I reduce the batch size? I'm currently trying the `python demo.py --vid_file sample_video.mp4 --output_folder output/ --display`

is it `MIN_NUM_FRAMES = 25`?

Edit: Sorry that was a low effort comment. Found it 
`vibe_batch_size` is the argument
